name: Payment / Plan Request
description: Submit payment details so we can create an order and issue a license.
title: "[PayLinkBridge] Payment Request — {plan} — {payment_reference}"
labels: ["paylink-request"]
body:
  - type: dropdown
    id: plan
    attributes:
      label: Select plan
      options:
        - label: Basic — One-time
          value: basic
        - label: Pro — Monthly subscription
          value: pro
        - label: Dev+ — Monthly subscription
          value: devplus
    validations:
      required: true

  - type: input
    id: amount
    attributes:
      label: Amount
      placeholder: "25.00"
    validations:
      required: true

  - type: dropdown
    id: currency
    attributes:
      label: Currency
      options:
        - label: AUD
          value: AUD
        - label: USD
          value: USD
    validations:
      required: true

  - type: input
    id: payment_reference
    attributes:
      label: Payment email or reference
      placeholder: "your-email-or-reference"
    validations:
      required: true

  - type: input
    id: fullName
    attributes:
      label: Full name
    validations:
      required: true

  - type: input
    id: date_of_birth
    attributes:
      label: Date of birth (YYYY-MM-DD)
    validations:
      required: true

  - type: textarea
    id: note
    attributes:
      label: Note / extra details

  - type: checkboxes
    id: terms
    attributes:
      label: Consent & Agreement
      options:
        - label: I consent to payment processing and verify my details are correct
          required: true
        - label: I agree to the terms and conditions
          required: true

  - type: input
    id: license_email
    attributes:
      label: Email for license delivery
      placeholder: "license-email"
      description: "License key will be sent to this address"
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional notes or requests
      placeholder: "Any special requests or notes about your order?"
